module.exports = {
  apps: [
    {
      name: 'clickynder',
      script: '.next/standalone/server.js',
      cwd: '/home/clickynder/app',
      instances: 1,
      exec_mode: 'fork',
      env_file: '/home/clickynder/app/.env',
      env: {
        NODE_ENV: 'production',
        PORT: '3002',
        HOSTNAME: '0.0.0.0',
        TZ: 'Asia/Jerusalem',
      },
      max_memory_restart: '1G',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/home/clickynder/app/logs/error.log',
      out_file: '/home/clickynder/app/logs/out.log',
      merge_logs: true,
      log_file: '/home/clickynder/app/logs/combined.log',
    },
    {
      name: 'clickynder-worker',
      script: 'worker/reminders-worker.js',
      cwd: '/home/clickynder/app',
      instances: 1,
      exec_mode: 'fork',
      env_file: '/home/clickynder/app/.env',
      env: {
        NODE_ENV: 'production',
        WORKER_API_URL: 'http://localhost:3002',
        TZ: 'Asia/Jerusalem',
      },
      max_memory_restart: '500M',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/home/clickynder/app/logs/worker-error.log',
      out_file: '/home/clickynder/app/logs/worker-out.log',
      merge_logs: true,
    },
  ],
};
